### ISSUE TITLE
React components touch and click events

### ISSUE THREAD

**Issue by symptom-Pg740** [phaserjs/template-react#1]
Hi there,

I'm encountering an issue with touch events on React components. When I use the onClick event handler, touch events don't seem to work. If I change it to onTouchStart, touch events work as expected, but mouse clicks no longer work.

Is this expected behavior? Should I add both onClick and onTouchStart to each button? Or is there something else I'm missing?

Thanks,

**Comment by photonstorm** [comment]
Hi - this was an issue introduced in Phaser v3.80.0, which we have just fixed in the v3.80.1 release. This template has been updated accordingly. Please pull down the new version of this template to resolve the issue.
